import streamlit as st
import pandas as pd
import plotly.express as px
from models import ComponentOption
from groq_service import GroqNLParser
from engines import FeasibilityEngine, CombinatorialOptimizer
from sub_agents import SubAgentExecutor

st.set_page_config(
    page_title="Autonomous AI Travel Agent",
    page_icon="✈️",
    layout="wide"
)

st.title("✈️ AI Budget-Constrained Autonomous Travel Agent")
st.caption("Powered by Groq LLM & Autonomous Combinatorial Optimization Engine")

st.sidebar.header("🕹️ User Input Parameters")

default_prompt = (
    "Plan a 5-day trip to Chicago (ORD) from Raleigh (RDU) for 2 adults and 2 kids "
    "with a strict maximum budget of $1000."
)

user_prompt = st.sidebar.text_area("Natural Language Request", value=default_prompt, height=120)

st.sidebar.markdown("---")
st.sidebar.subheader("📦 Inventory Search Criteria")

flight_price = st.sidebar.slider("Sample Flight Cost ($)", 150, 600, 240, 10)
hotel_price = st.sidebar.slider("Sample Hotel Cost ($)", 150, 600, 260, 10)

run_button = st.sidebar.button("🚀 Run Autonomous Agent", type="primary", use_container_width=True)

if run_button:
    with st.spinner("🤖 Groq AI Parsing Request & Searching Inventory..."):
        try:
            parser = GroqNLParser()
            constraints = parser.parse_user_prompt(user_prompt)
        except Exception as e:
            st.error(f"Error parsing request with Groq API: {e}")
            st.stop()

    st.subheader("1. Parsed Hard & Soft Constraints")
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Origin", constraints.origin)
    col2.metric("Destination", constraints.destination)
    col3.metric("Duration", f"{constraints.duration_days} Days")
    col4.metric("Travelers", f"{constraints.adults}A / {constraints.children}C")
    col5.metric("Hard Budget Cap", f"${constraints.max_budget:,.2f}")

    # Available dynamic options
    available_flights = [
        ComponentOption("F1", "Flight", "Frontier Airlines", float(flight_price), 0.75, {"route": f"{constraints.origin}-{constraints.destination} Direct"}),
        ComponentOption("F2", "Flight", "American Airlines", float(flight_price + 110), 0.88, {"route": f"{constraints.origin}-{constraints.destination} Direct"}),
    ]

    available_hotels = [
        ComponentOption("H1", "Hotel", "Holiday Inn Express", float(hotel_price), 0.78, {"room_type": "Standard 2 Double"}),
        ComponentOption("H2", "Hotel", "Hyatt Regency Loop", float(hotel_price + 140), 0.90, {"room_type": "2 Queen Suite"}),
    ]

    min_baseline = min(f.cost for f in available_flights) + min(h.cost for h in available_hotels) + 150.0
    is_feasible, deficit = FeasibilityEngine.evaluate(constraints, min_baseline)

    if not is_feasible:
        st.error(f"❌ Trip NOT Feasible under ${constraints.max_budget:,.2f} Cap! (Shortfall: ${abs(deficit):,.2f})")
        st.warning("Alternative Options Generated by Agent:")
        alts = FeasibilityEngine.propose_alternatives(constraints)
        st.table(pd.DataFrame(alts))
    else:
        st.success("✅ Feasibility Assessment Passed!")
        
        optimizer = CombinatorialOptimizer(available_flights, available_hotels)
        bundle = optimizer.find_optimal_bundle(constraints)

        if bundle:
            st.markdown("---")
            st.subheader("2. Optimized Trip Bundle Breakdown")

            # Budget Allocation Dataframe for Charts
            budget_data = {
                "Category": ["Flight", "Hotel", "Food Allowance", "Transit Allowance", "Activities", "Contingency"],
                "Amount ($)": [
                    bundle.flight.cost,
                    bundle.hotel.cost,
                    bundle.food_allowance,
                    bundle.transit_allowance,
                    bundle.activity_allowance,
                    bundle.contingency_reserve
                ]
            }
            df_budget = pd.DataFrame(budget_data)

            col_left, col_right = st.columns([1, 1])

            with col_left:
                st.write("**Cost Distribution Breakdown**")
                fig = px.pie(
                    df_budget, 
                    values="Amount ($)", 
                    names="Category", 
                    hole=0.4,
                    color_discrete_sequence=px.colors.qualitative.Set3
                )
                st.plotly_chart(fig, use_container_width=True)

            with col_right:
                st.write("**Budget Cap Utilization**")
                progress_val = min(1.0, bundle.total_cost / constraints.max_budget)
                st.progress(progress_val)
                st.metric("Total Guaranteed Cost", f"${bundle.total_cost:,.2f}", delta=f"${constraints.max_budget - bundle.total_cost:,.2f} Surplus")

                st.info(f"**Selected Flight:** {bundle.flight.provider} (${bundle.flight.cost})")
                st.info(f"**Selected Stay:** {bundle.hotel.provider} (${bundle.hotel.cost})")

            # AI Summary
            with st.spinner("Writing AI Justification..."):
                summary_input = f"Flight: {bundle.flight.provider} (${bundle.flight.cost}), Hotel: {bundle.hotel.provider} (${bundle.hotel.cost}), Total: ${bundle.total_cost:.2f}"
                ai_justification = parser.summarize_itinerary_reasoning(summary_input)
                st.markdown(f"**🤖 Groq AI Recommendation Reasoning:**\n*{ai_justification}*")

            # Execution Step
            st.markdown("---")
            st.subheader("3. Autonomous Sub-Agent Booking Execution")

            if st.button("🔒 Confirm & Execute Autonomous Bookings", type="primary"):
                executor = SubAgentExecutor(max_budget_ceiling=constraints.max_budget)
                try:
                    booking_result = executor.execute_booking(bundle)
                    st.balloons()
                    st.success("🎉 All Reservations Successfully Confirmed & Guaranteed!")
                    
                    res_col1, res_col2, res_col3 = st.columns(3)
                    res_col1.metric("Booking Status", booking_result["status"])
                    res_col2.metric("Flight PNR", booking_result["flight_pnr"])
                    res_col3.metric("Hotel PNR", booking_result["hotel_pnr"])
                except Exception as ex:
                    st.error(f"Booking execution failed: {ex}")